SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES]
ORDER BY [NOME];

SELECT [ESTADO], [NOME] FROM [TABELA DE CLIENTES];

SELECT * FROM [TABELA DE PRODUTOS];

SELECT [NOME], [CPF], [ESTADO] 
FROM [TABELA DE CLIENTES];

SELECT [NOME] AS [NOME DO CLIENTE], [CPF], [ESTADO] AS [UF]
FROM [TABELA DE CLIENTES];

SELECT [NOME] AS [NOME DO CLIENTE], [PRIMEIRA COMPRA], [ESTADO] AS [UF]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT [MATRICULA] AS [INDENTIFICADOR], [NOME] AS [NOME DO VENDEDOR]
FROM [TABELA DE VENDEDORES];

SELECT [SABOR] FROM [TABELA DE PRODUTOS];

SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] = 7.00;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] > 7.00;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] <= 7.00;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] = 7.00;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] = 'Lata';

SELECT DISTINCT [EMBALAGEM] FROM [TABELA DE PRODUTOS];

SELECT [NOME], [DATA DE NASCIMENTO]
FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31'

SELECT [NOME], [DATA DE NASCIMENTO]
FROM [TABELA DE CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995'

SELECT [NOME], [BAIRRO]
FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca';

SELECT [NOME], [ESTADO], [PRIMEIRA COMPRA]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1 AND [ESTADO] = 'SP';

SELECT * FROM [TABELA DE VENDEDORES];

SELECT * FROM [TABELA DE VENDEDORES]
WHERE [PERCENTUAL COMISSAO] <= '0.08';

SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] = 'Lata' AND [PRECO DE LISTA] <= '6';

SELECT * FROM [TABELA DE CLIENTES];

SELECT * FROM [TABELA DE CLIENTES]
WHERE NOT[ESTADO] = 'RJ' OR [ESTADO] = 'SP';

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9
WHERE [EMBALAGEM] = 'Lata';

SELECT * FROM [TABELA DE PRODUTOS];

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Garrafa', [PRECO DE LISTA] = 8.10
WHERE [CODIGO DO PRODUTO] = '1088126';

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327'